language: cpp

sudo: required

os:
  - linux
  - osx

dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq cmake qt5-default; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5; fi

before_script:
  - CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On" ./configure
  
script:
  - cd build
  - make -j 8
  - make test
