language: cpp

sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  matrix:
    - CMAKE_CONFIGURATION=release
    - CMAKE_CONFIGURATION=debug

matrix:
  exclude:
  - os: osx
    compiler: gcc

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -qq cmake qt5-default; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install qt5; fi

before_script:
  - ./configure
  - if [ $CMAKE_CONFIGURATION == release ]; then CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On" ./configure; fi
  - if [ $CMAKE_CONFIGURATION == debug ]; then CMAKE_OPTIONS="-DOPTION_BUILD_EXAMPLES=On" ./configure debug; fi

script:
  - cmake --build build -- -j 8
  - cmake --build --target test build
